USE calcit; 

CREATE TABLE USER (
  user_id int NOT NULL AUTO_INCREMENT,
  login varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  PRIMARY KEY (user_id)
);

CREATE TABLE BMI (
bmi_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
bmi_value DOUBLE NOT NULL,
timestamp varchar(255) NOT NULL,
user_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES USER(user_id)
);

CREATE TABLE PPM (
ppm_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ppm_value DOUBLE NOT NULL,
timestamp TIMESTAMP NOT NULL,
user_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES USER(user_id)
);

CREATE TABLE YMCA (
ymca_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ymca_value DOUBLE NOT NULL,
timestamp TIMESTAMP NOT NULL,
user_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES USER(user_id)
);

CREATE TABLE PRAL (
pral_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
pral_value DOUBLE NOT NULL,
timestamp TIMESTAMP NOT NULL,
user_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES USER(user_id)
);